### ISSUE TITLE
Issue with temp_rollout.py

### ISSUE THREAD

**Issue by TimHuDi** [ucb-bar/NeuroVectorizer#10]
Hi @AmeerHajAli:
     I'm done with configure.sh and preprocess.sh, when i run python temp_rollout.py checkpoints/checkpoint_100/checkpoint-100 --rollout_dir "./tests" --compile , i get the below error in error.txt.
     AttributeError: 'NonoeType' object has no attribute 'restore'.

Best Regards
TimHu

**Comment by AmeerHajAli** [comment]
Hi TimHu!
Thanks for asking.
Which ray version are you using? and which dependencies did you install?

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
       I use ray 0.8.6, tensorflow 2.3.0. I install dependencies : **py-spy, jsonschema, colorama, filelock, protobuf, msgpack, pyyaml, grpcio, redis, aiohttp, numpy, click, google**  for ray. If I train the RL model, and use the generated checkpoint, the inference is ok.
Thanks for your sharing.

Best Regards
TimHu

**Comment by AmeerHajAli** [comment]
I think it is because it was generated with an older ray version.

**Comment by AmeerHajAli** [comment]
Can you check if it works with ray 0.8.4?

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by TimHuDi** [comment]
Hi @AmeerHajAli:
I check it with ray 0.8.4 , it works. Thanks for your sharing.

Best Regards
TimHu

**Comment by AmeerHajAli** [comment]
Thanks!
